#!/usr/bin/python
import urllib2, re, sys
from lxml.html import fromstring, tostring
from PyQt4 import QtCore, QtGui
from ui import steamfriendsui

class FetchFriends(QtGui.QMainWindow, steamfriendsui.Ui_SteamFriendsStatus):
	def __init__(self):
		QtGui.QWidget.__init__(self)
		self.setupUi(self)
		self.connect(self.FetchButton, QtCore.SIGNAL("clicked()"), self.get_friend_status)
		self.connect(self.ListSteamFriends, QtCore.SIGNAL("doubleClicked(QModelIndex)"),self.get_server_data)
	def get_server_data(self):
		""" Get server information """
		pass
	def get_friend_status(self):
		""" Populates the list, sends a request to Steam community
			pages for friends list """
		steamid = self.SteamUsername.displayText()
		steamid = str(steamid)
		url = ''
		if re.search(r'\d',steamid):
			url = 'http://steamcommunity.com/profiles/%s/friends' % (steamid)
		elif re.search(r'\w',steamid):
			url = 'http://steamcommunity.com/id/%s/friends' % (steamid)
		else: 
			QtGui.QMessageBox.information(self,"Could not launch space rodents! Please try again!","Our specially trained space rodents on rocket skates could not be launched to fetch your list of friends!\n\nPlease try again by using the following:\nShort alias: http://steamcommunity.com/id/$alias\nID: http://steamcommunity.com/id/$id\n\nPlease hurry! Once they're finished eating their fill of expensive space cheese they'll be plotting to take over the world!")
		
		content = urllib2.build_opener()
		content.addheaders = [('User-agent', 'Mozilla/5.0')]
		try:
			data = content.open(url).read()
			content.close()
		except ValueError, e:
			print 'Unknown URL'
			return 
		except urllib2.URLError, e:
			print 'Failed to connect'
			print 'Reason: ',e.reason
			return
		except urllib2.HTTPError, e:
			print 'Remote server error'
			print 'Error code: ',e.code
			return

		doc = fromstring(data)
		doc.make_links_absolute(url)

		c = 0
		line = ''
		for f_ingame in [i.text_content() for i in doc.find_class('linkFriend_in-game')]:
				f_ingame = re.sub('\s-\sJoin', '', re.sub('In-Game', '', f_ingame))
				if c == 1:	
					line += "    %s\n\t\tIn-game" % (f_ingame)
					self.ListSteamFriends.addItem(line)
					c = 0
					line = ''
				else:
					line += "%s\n" % (f_ingame)
					c += 1
		for i in doc.find_class('linkFriend_online'):
			line = "%s\n\t\tOnline" % (i.text_content())
			self.ListSteamFriends.addItem(line)


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    SteamFriends = FetchFriends()
    SteamFriends.show()
    sys.exit(app.exec_())
